[tool.poetry]
name = "insta-clone"
version = "0.1.0"
description = ""
authors = ["mr-Thamaraiselvam <thamaraiselvamc@gmail.com>"]
readme = "README.md"
package-mode = false


[tool.poetry.dependencies]
python = ">=3.13"
django = "^5.0.1"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
